### ISSUE TITLE
Add an "All Categories" page.

### ISSUE THREAD

**Issue by Infinizhen** [LittleCodingFox/StaticWiki#21]
It would be great for staticwiki to have a page showing a link to all our Categories.

It may be related with #17 .

This page would list all the categories in our wiki for an easier access.

**Comment by LittleCodingFox** [comment]
Good tip. I'll work on this soon!

**Comment by LittleCodingFox** [comment]
I added this to the master branch recently. StaticWiki should generate a `CategoryList` file with the extension of your theme. In addition to that, it also has support for multiple theme files now. Your `staticwiki.ini` file might not work but it's easy to change, just look at the sample file.

Let me know if you need anything 👍
