### ISSUE TITLE
How to compile from source?

### ISSUE THREAD

**Issue by Rinfinity1** [LittleCodingFox/StaticWiki#23]
I want to access the `{TOC}` features but have no idea how to compile C# sourcecode, I tried using Visualstudio but no build button appeared when I opened the .SLN.

**Comment by LittleCodingFox** [comment]
Hey I just made a release with a windows binary, let me know if you need anything else!

https://github.com/LittleCodingFox/StaticWiki/releases/tag/1.0.0-pre6

**Comment by Rinfinity1** [comment]
I added some [toc]Contents[/toc] tags to different parts of the page but no TOC is generated? I'm using the basic theme, the {TOC} _is_ there, it's just not creating one.

**Comment by LittleCodingFox** [comment]
Does it show any text before the main content? I tried here and it seems to work!

Here's an example toc block you could try:
```
[toc]
[template name="toc"]
	[templateitem]
		[templateitemtag name="page-name"]Templates[/templateitemtag]
		[templateitemtag name="page-link"]Templates[/templateitemtag]
	[/templateitem]
[/template]
[/toc]
```

**Comment by Rinfinity1** [comment]
This is all that appears for me, I'm probably doing something wrong that you'll realize instantly, I just don't know what that detail is from my POV.

Everything is stock, it's the same as the files provided in 1.0.0-pre6, except I changed the toc template in the theme.html to the code you provided above.
![image](https://user-images.githubusercontent.com/58800515/168487942-3f03b7d2-52c6-4fdb-89d5-5ef1a509c802.png)

**Comment by LittleCodingFox** [comment]
Right, the code I sent you is supposed to go to the page you want the TOC to show up, so e.g., after the title and category in the index.md file, you add that code I showed you, and there should be a Templates link added which is the TOC!

Let me know if you need any further help. Don't forget to undo the changes on the theme!

**Comment by LittleCodingFox** [comment]
Hi @Rinfinity1 , do you need any further help, or should I close this?

**Comment by LittleCodingFox** [comment]
Closing since no more activity
